import * as fs from 'fs';
import * as path from 'path';
import * as yaml from 'js-yaml';
import { Domain, getCatalog, inferDomain, CatalogOption } from './catalogs';

// The on-disk Blueprint: a domain + goal + the level-by-level decision tree, persisted as YAML in
// .bimax/blueprints/<slug>.yaml (git-tracked, hand-editable). Generated by Sketch Mode, consumed by
// the Build stage (beast mode). Mirrors the recipe loader's storage model.

export interface BlueprintOption {
  id: string;
  title: string;
  note: string;
  /** Where this option came from — builtin catalog or imported from the web. */
  source: 'builtin' | 'web';
  /** For web-imported options: the URL it was fetched from. */
  url?: string;
}

export interface BlueprintLevel {
  id: string;
  title: string;
  options: BlueprintOption[];
  /** The selected option id (empty until the user/agent decides). */
  selected: string;
  /** Free-text override/note that customizes or MIXES options — honored verbatim at build. */
  override?: string;
}

export interface Blueprint {
  slug: string;
  domain: Domain;
  goal: string;
  build: string;
  verify: string;
  levels: BlueprintLevel[];
  createdAt: string;
  filePath: string; // set by the engine, not stored in YAML
}

const BLUEPRINT_DIR = '.bimax/blueprints';

function slugify(s: string): string {
  return s.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 60) || 'blueprint';
}

export class BlueprintEngine {
  constructor(private projectRoot: string) {}

  get dir(): string {
    return path.join(this.projectRoot, BLUEPRINT_DIR);
  }

  private ensureDir(): void {
    fs.mkdirSync(this.dir, { recursive: true });
  }

  /** Instantiate a fresh Blueprint from a domain catalog (or an inferred domain) and persist it. */
  create(goal: string, domainHint?: string): Blueprint {
    const domain: Domain = (domainHint && getCatalog(domainHint)?.domain) || inferDomain(goal);
    const cat = getCatalog(domain)!;
    const levels: BlueprintLevel[] = cat.levels.map(l => ({
      id: l.id,
      title: l.title,
      options: l.options.map(o => ({ ...o, source: 'builtin' as const })),
      selected: l.default ?? '',
    }));
    const bp: Blueprint = {
      slug: slugify(goal),
      domain,
      goal,
      build: cat.build,
      verify: cat.verify,
      levels,
      createdAt: new Date().toISOString(),
      filePath: '',
    };
    return this.save(bp);
  }

  save(bp: Blueprint): Blueprint {
    this.ensureDir();
    const filePath = path.join(this.dir, `${bp.slug}.yaml`);
    const { filePath: _omit, ...persist } = bp;
    fs.writeFileSync(filePath, yaml.dump(persist, { lineWidth: 100, noRefs: true }), 'utf8');
    return { ...bp, filePath };
  }

  load(slug: string): Blueprint | null {
    const filePath = path.join(this.dir, `${slug}.yaml`);
    try {
      const parsed = yaml.load(fs.readFileSync(filePath, 'utf8')) as any;
      if (!parsed || typeof parsed !== 'object') return null;
      return { ...(parsed as Blueprint), slug: parsed.slug ?? slug, filePath };
    } catch {
      return null;
    }
  }

  list(): { slug: string; domain: string; goal: string }[] {
    if (!fs.existsSync(this.dir)) return [];
    return fs.readdirSync(this.dir)
      .filter(f => f.endsWith('.yaml') || f.endsWith('.yml'))
      .map(f => this.load(path.basename(f, path.extname(f))))
      .filter((b): b is Blueprint => b !== null)
      .map(b => ({ slug: b.slug, domain: b.domain, goal: b.goal }));
  }

  delete(slug: string): boolean {
    const filePath = path.join(this.dir, `${slug}.yaml`);
    try { fs.unlinkSync(filePath); return true; } catch { return false; }
  }

  private mutate(slug: string, fn: (l: BlueprintLevel, bp: Blueprint) => void, levelId: string): Blueprint | { error: string } {
    const bp = this.load(slug);
    if (!bp) return { error: `No blueprint "${slug}". Use list to see saved ones.` };
    const level = bp.levels.find(l => l.id === levelId || l.title.toLowerCase() === levelId.toLowerCase());
    if (!level) return { error: `No level "${levelId}" in "${slug}". Levels: ${bp.levels.map(l => l.id).join(', ')}.` };
    fn(level, bp);
    return this.save(bp);
  }

  /** Pick an option at a level. */
  select(slug: string, levelId: string, optionId: string): Blueprint | { error: string } {
    return this.mutate(slug, (level) => {
      const opt = level.options.find(o => o.id === optionId || o.title.toLowerCase() === optionId.toLowerCase());
      level.selected = opt ? opt.id : optionId; // allow selecting a not-yet-listed id; build will honor it
    }, levelId);
  }

  /** Set a free-text override/note at a level (customizes or MIXES options). */
  override(slug: string, levelId: string, text: string): Blueprint | { error: string } {
    return this.mutate(slug, (level) => { level.override = text; }, levelId);
  }

  /** Add a new option (e.g. imported from the web) at a level and select it if asked. */
  importOption(slug: string, levelId: string, opt: Omit<BlueprintOption, 'source'> & { url?: string }, select = true): Blueprint | { error: string } {
    return this.mutate(slug, (level) => {
      const newOpt: BlueprintOption = { id: opt.id, title: opt.title, note: opt.note, source: 'web', url: opt.url };
      const existing = level.options.findIndex(o => o.id === newOpt.id);
      if (existing >= 0) level.options[existing] = newOpt; else level.options.push(newOpt);
      if (select) level.selected = newOpt.id;
    }, levelId);
  }

  /** Render a Blueprint as readable markdown (for showing the user / the build prompt). */
  format(bp: Blueprint): string {
    const cat = getCatalog(bp.domain);
    const lines: string[] = [
      `# Blueprint: ${bp.goal}`,
      ``,
      `**Domain:** ${cat?.title ?? bp.domain}  ·  **Slug:** \`${bp.slug}\`  ·  **File:** \`${path.relative(this.projectRoot, bp.filePath)}\``,
      ``,
    ];
    for (const l of bp.levels) {
      const sel = l.options.find(o => o.id === l.selected);
      const selLabel = sel ? sel.title : (l.selected || '— undecided —');
      lines.push(`### ${l.title}  →  **${selLabel}**${sel?.source === 'web' ? ' 🌐' : ''}`);
      if (sel) lines.push(`  ${sel.note}`);
      const others = l.options.filter(o => o.id !== l.selected);
      if (others.length) lines.push(`  _options:_ ${others.map(o => o.title).join(' · ')}`);
      if (l.override) lines.push(`  _override:_ ${l.override}`);
      lines.push('');
    }
    lines.push(`**Build:** ${bp.build}`, `**Verify:** ${bp.verify}`);
    return lines.join('\n');
  }

  /** A compact instruction block the Build stage feeds to the executor (selections + overrides). */
  buildBrief(bp: Blueprint): string {
    const decided = bp.levels.map(l => {
      const sel = l.options.find(o => o.id === l.selected);
      const choice = sel ? sel.title : (l.selected || 'choose a sensible default');
      const ov = l.override ? ` [OVERRIDE — honor verbatim: ${l.override}]` : '';
      return `- ${l.title}: ${choice}${ov}`;
    }).join('\n');
    return [
      `Build this ${bp.domain} per the Blueprint. Honor every selection AND every OVERRIDE exactly.`,
      ``,
      `Goal: ${bp.goal}`,
      ``,
      `Decisions:`,
      decided,
      ``,
      `How to build: ${bp.build}`,
      `How to verify: ${bp.verify}`,
    ].join('\n');
  }
}

let _engine: BlueprintEngine | null = null;
export function getBlueprintEngine(): BlueprintEngine | null { return _engine; }
export function setBlueprintEngine(e: BlueprintEngine): void { _engine = e; }
