/**
 * Manual macOS mouse regression: exercise Finder through the same visible native-cursor runtime
 * used by ComputerTool.
 *
 * Builds its own disposable fixture in the system temp directory, so `npm run test:computer:finder`
 * runs with no arguments. Pass an absolute path to use an existing fixture instead; one supplied
 * that way is never deleted.
 *
 * It previously REQUIRED that argument while the npm script passed none, so the wired-up command
 * could not run at all — it threw a usage error before reaching a single assertion. A test surface
 * that cannot be invoked is indistinguishable from one that passes: nothing was watching this path.
 */
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { BimaxComputerRuntime, DesktopResult } from '../../src/capabilities/mac/desktop.runtime';

const suppliedFixture = process.argv[2];
const fixture = suppliedFixture || fs.mkdtempSync(path.join(os.tmpdir(), 'bimax-smoke-finder-'));
if (!suppliedFixture) {
  for (const dir of ['DoubleClickFolder', 'DropTarget', 'MultiTarget']) {
    fs.mkdirSync(path.join(fixture, dir), { recursive: true });
  }
  for (const file of ['control-unselected.txt', 'alpha-drag.txt',
    'red-select.txt', 'green-select.txt', 'blue-select.txt']) {
    fs.writeFileSync(path.join(fixture, file), `bimax finder smoke ${file}\n`);
  }
}

function ok(result: DesktopResult): DesktopResult {
  if (!result.ok) throw new Error(result.error || result.summary);
  return result;
}

function point(result: DesktopResult, label: string): { x: number; y: number } {
  const element = (result.elements || []).find((candidate: any) =>
    String(candidate?.label || candidate?.value || '').trim() === label && candidate?.frame,
  ) as any;
  if (!element?.frame) {
    const labels = (result.elements || []).map((candidate: any) => candidate?.label).filter(Boolean).slice(0, 30);
    throw new Error(`no visible frame for ${label}; visible labels: ${labels.join(', ')}`);
  }
  return {
    x: Math.round(Number(element.frame.x) + Number(element.frame.w) / 2),
    y: Math.round(Number(element.frame.y) + Number(element.frame.h) / 2),
  };
}

function physical(result: DesktopResult, action: string): void {
  if ((result.details as any)?.path !== 'native-global-cgevent') {
    throw new Error(`${action} did not use the visible native cursor`);
  }
}

async function observe(runtime: BimaxComputerRuntime, query?: string) {
  return ok(await runtime.run({ action: 'observe', query, maxElements: 600 }));
}

/**
 * Raw-coordinate actions must be planned from a frame the runtime still considers current.
 *
 * A coordinate cannot be re-grounded — that is exactly why the stale-frame guard keeps refusing raw
 * x/y while re-grounding named targets — so when the preceding step's accessibility events are still
 * draining, the correct answer is the one the refusal itself gives: let it settle, observe again,
 * re-read the geometry, and re-issue.
 *
 * Measured on 2026-08-06, which is why this settles rather than spinning: after three cmd-clicks the
 * epoch had reached 27 and then did NOT move again through 3s of idle sampling (+0 at every step),
 * and a scroll planned from the following observe succeeded first time. The burst is generated by
 * the actions themselves and drains in well under the delay below; it is not a continuously-updating
 * app, so a tight retry loop was simply re-entering the same burst it was waiting out.
 */
async function fromFreshFrame<T>(
  runtime: BimaxComputerRuntime,
  plan: (screen: DesktopResult) => Promise<T>,
): Promise<T> {
  const attempts = 3;
  for (let attempt = 1; ; attempt++) {
    const screen = await observe(runtime);
    try {
      return await plan(screen);
    } catch (error: any) {
      const stale = /accessibility state changed|fresh screenshot of the exact target window/i
        .test(String(error?.message || ''));
      if (!stale || attempt >= attempts) throw error;
      await new Promise(resolve => setTimeout(resolve, 250));
    }
  }
}

async function main() {
  if (process.platform !== 'darwin') throw new Error('Finder mouse smoke is macOS-only');
  if (!path.isAbsolute(fixture) || !fs.statSync(fixture).isDirectory()) throw new Error('fixture must be an existing absolute directory');
  const runtime = new BimaxComputerRuntime();
  const checks: Record<string, unknown> = {};
  try {
    ok(await runtime.run({ action: 'status' }));
    ok(await runtime.run({ action: 'open', app: 'Finder' }));
    ok(await runtime.run({ action: 'key', combo: 'cmd+shift+g' }));
    ok(await runtime.run({ action: 'type', text: fixture }));
    ok(await runtime.run({ action: 'key', combo: 'enter' }));
    let screen = await observe(runtime, 'DoubleClickFolder');
    checks.navigation = { matched: screen.verification?.matched, screenshot: screen.screenshot };
    if (!screen.verification?.matched) throw new Error('fixture contents did not appear after Go to Folder');

    const doubled = ok(await runtime.run({ action: 'click', query: 'DoubleClickFolder', count: 2 }));
    physical(doubled, 'double-click');
    screen = await observe(runtime, 'DoubleClickFolder');
    // The destination window title is also "DoubleClickFolder"; only the old icon remaining would
    // mean the double-click failed.
    const openedFolder = !(screen.elements || []).some((candidate: any) =>
      candidate?.role === 'AXImage'
      && String(candidate?.label || candidate?.value || '').trim() === 'DoubleClickFolder');
    if (!openedFolder) throw new Error('DoubleClickFolder was still visible after double-click');
    checks.doubleClick = { physical: true, opened: true, screenshot: screen.screenshot };

    ok(await runtime.run({ action: 'key', combo: 'cmd+[' }));
    screen = await observe(runtime, 'control-unselected.txt');
    if (!screen.verification?.matched) throw new Error('Back did not return to the fixture folder');
    const context = ok(await runtime.run({ action: 'click', query: 'control-unselected.txt', button: 'right' }));
    physical(context, 'right-click');
    // The menu itself is the evidence, because it is now observable.
    //
    // This used to assert `progressCheck.frameChanged` on the theory that a context menu is absent
    // from the AX tree, so only pixels could prove it. Both halves were wrong, and in opposite
    // directions: the menu is fully published inside the owned window's element list, while
    // frameChanged is measured against a WINDOW-scoped capture and a menu may be drawn beyond that
    // window's bounds — so the proxy could fail on a menu that had opened perfectly.
    const menu = await observe(runtime);
    const commands = (menu.elements || [])
      .filter((element: any) => element?.role === 'AXMenuItem')
      .map((element: any) => String(element?.label || '').trim())
      .filter(Boolean);
    if (commands.length === 0) {
      throw new Error('right-click delivered but the Finder context menu published no named commands');
    }
    ok(await runtime.run({ action: 'key', combo: 'escape' }));
    screen = await observe(runtime, 'control-unselected.txt');
    const stillOpen = (screen.elements || []).filter((element: any) => element?.role === 'AXMenuItem').length;
    if (stillOpen > 0) throw new Error(`Escape left ${stillOpen} context-menu commands on screen`);
    if (screen.verification?.matched !== true) throw new Error('the fixture folder was not visible after dismissing the menu');
    checks.rightClick = {
      physical: true, commandCount: commands.length, sample: commands.slice(0, 6),
      dismissed: true, screenshot: context.screenshot,
    };

    const dragged = await fromFreshFrame(runtime, async beforeDrag => {
      const from = point(beforeDrag, 'alpha-drag.txt');
      const to = point(beforeDrag, 'DropTarget');
      return ok(await runtime.run({ action: 'drag', x: from.x, y: from.y, toX: to.x, toY: to.y }));
    });
    physical(dragged, 'drag');
    const singleMoved = fs.existsSync(path.join(fixture, 'DropTarget', 'alpha-drag.txt'))
      && !fs.existsSync(path.join(fixture, 'alpha-drag.txt'));
    if (!singleMoved) throw new Error('native drag completed but alpha-drag.txt did not move into DropTarget');
    checks.dragDrop = { physical: true, moved: true, screenshot: dragged.screenshot };

    for (const label of ['red-select.txt', 'green-select.txt', 'blue-select.txt']) {
      await observe(runtime, label);
      const selected = ok(await runtime.run({ action: 'click', query: label, modifier: ['cmd'] }));
      physical(selected, `cmd-click ${label}`);
    }
    const groupDrag = await fromFreshFrame(runtime, async frame => {
      const groupFrom = point(frame, 'blue-select.txt');
      const groupTo = point(frame, 'MultiTarget');
      return ok(await runtime.run({ action: 'drag', x: groupFrom.x, y: groupFrom.y, toX: groupTo.x, toY: groupTo.y }));
    });
    physical(groupDrag, 'multi-select drag');
    const selectedNames = ['red-select.txt', 'green-select.txt', 'blue-select.txt'];
    const groupMoved = selectedNames.every(name => fs.existsSync(path.join(fixture, 'MultiTarget', name)))
      && fs.existsSync(path.join(fixture, 'control-unselected.txt'));
    if (!groupMoved) throw new Error('Cmd multi-select drag did not move exactly the three selected files');
    checks.multiSelectDrag = { physical: true, movedThree: true, unselectedPreserved: true, screenshot: groupDrag.screenshot };

    const scrolled = await fromFreshFrame(runtime, async frame => {
      const scrollPoint = { x: Math.round((frame.width || 800) * 0.7), y: Math.round((frame.height || 600) * 0.7) };
      return ok(await runtime.run({ action: 'scroll', ...scrollPoint, dy: 500 }));
    });
    physical(scrolled, 'scroll');
    checks.scroll = { physical: true, freshFrame: !!scrolled.screenshot, screenshot: scrolled.screenshot };

    console.log(JSON.stringify({ fixture, checks }, null, 2));
  } finally {
    await runtime.dispose();
    // Only remove what this script created. A fixture handed in on the command line belongs to the
    // caller and is left exactly where it is.
    if (!suppliedFixture) fs.rmSync(fixture, { recursive: true, force: true });
  }
}

main().catch(error => {
  console.error(error instanceof Error ? error.stack || error.message : String(error));
  process.exitCode = 1;
});
