import { globalCommandRegistry } from './registry';
import { execSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';
import { getActiveTodos } from '../../tools/implementations/todo.tool';

/**
 * /changelog — Generate a structured session changelog.
 *
 * /changelog          — show in terminal
 * /changelog export   — write to ./CHANGES-<timestamp>.md
 *
 * Collects: git diff stats (files changed, +/- lines), completed todos (goal + key decisions).
 */

function runGit(cmd: string, cwd: string): string {
  try {
    return execSync(cmd, { cwd, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
  } catch {
    return '';
  }
}

function buildChangelog(cwd: string): string {
  const now = new Date();
  const dateStr = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')} ${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`;

  // --- Git diff stats: what changed this session ---
  // --numstat gives machine-readable "<added>\t<deleted>\t<path>" per file, so we can report
  // exact +/- counts (e.g. "+42, -18") instead of git's vague "N lines changed" histogram.
  const numStat = runGit('git diff HEAD --numstat', cwd);
  const shortStat = runGit('git diff HEAD --shortstat', cwd);

  const changedFiles: string[] = [];
  if (numStat) {
    for (const line of numStat.split('\n')) {
      const m = line.match(/^(\d+|-)\t(\d+|-)\t(.+)$/);
      if (!m) continue;
      const [, added, deleted, file] = m;
      // "-" in added/deleted means a binary file; show that rather than a misleading "+0, -0".
      const counts = added === '-' || deleted === '-' ? 'binary' : `+${added}, -${deleted}`;
      changedFiles.push(`- \`${file.trim()}\` (${counts})`);
    }
  }

  // Also check untracked / newly staged files
  const untracked = runGit('git ls-files --others --exclude-standard', cwd);
  if (untracked) {
    for (const f of untracked.split('\n').filter(Boolean)) {
      changedFiles.push(`- \`${f}\` (new, untracked)`);
    }
  }

  // --- Todos: goal and key decisions from completed items ---
  const todos = getActiveTodos();
  const completed = todos.filter(t => t.status === 'completed').map(t => `- ${t.content}`);
  const open = todos.filter(t => t.status !== 'completed').map(t => `- ${t.content}`);

  // --- Assemble ---
  const sections: string[] = [`## Session Changelog — ${dateStr}`, ''];

  if (changedFiles.length > 0) {
    sections.push('### Files Modified');
    sections.push(changedFiles.join('\n'));
    if (shortStat) sections.push(`\n_${shortStat}_`);
    sections.push('');
  } else {
    sections.push('### Files Modified');
    sections.push('_No uncommitted changes detected (all changes may already be committed)._');
    sections.push('');
  }

  if (completed.length > 0) {
    sections.push('### Completed Tasks');
    sections.push(completed.join('\n'));
    sections.push('');
  }

  if (open.length > 0) {
    sections.push('### Still Open');
    sections.push(open.join('\n'));
    sections.push('');
  }

  sections.push('_Generated by BiMax /changelog_');
  return sections.join('\n');
}

globalCommandRegistry.register({
  name: '/changelog',
  description: 'Generate a structured session changelog (files changed, tasks, decisions)',
  category: 'Session & Context',
  execute: async (args, context) => {
    const cwd = context.cwd || process.cwd();
    const sub = (args[0] || '').toLowerCase();

    const content = buildChangelog(cwd);

    if (sub === 'export') {
      const now = new Date();
      const stamp = `${now.getFullYear()}${String(now.getMonth() + 1).padStart(2, '0')}${String(now.getDate()).padStart(2, '0')}-${String(now.getHours()).padStart(2, '0')}${String(now.getMinutes()).padStart(2, '0')}`;
      const outPath = path.join(cwd, `CHANGES-${stamp}.md`);
      try {
        fs.writeFileSync(outPath, content, 'utf8');
        return { type: 'message', level: 'success', content: `Changelog exported to ${outPath}` };
      } catch (e: any) {
        return { type: 'message', level: 'error', content: `Failed to write changelog: ${e.message}` };
      }
    }

    return { type: 'message', level: 'info', content: content };
  },
});
